"""Add Learner, Tracking, Tutor and ExpertUser tables

Revision ID: 16068309bdb8
Revises: bc4cda91a030
Create Date: 2025-12-23 02:00:58.044928+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16068309bdb8'
down_revision = 'bc4cda91a030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=255), nullable=True),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.Column('hopital_affiliation', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_email'), 'experts', ['email'], unique=True)
    op.create_index(op.f('ix_experts_id'), 'experts', ['id'], unique=False)
    op.create_table('learners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('niveau_etudes', sa.String(length=50), nullable=True),
    sa.Column('specialite_visee', sa.String(length=100), nullable=True),
    sa.Column('langue_preferee', sa.String(length=10), nullable=True),
    sa.Column('date_inscription', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learners_email'), 'learners', ['email'], unique=True)
    op.create_index(op.f('ix_learners_id'), 'learners', ['id'], unique=False)
    op.create_index(op.f('ix_learners_matricule'), 'learners', ['matricule'], unique=True)
    op.create_table('learner_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.String(length=100), nullable=True),
    sa.Column('date_obtention', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learner_cognitive_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=True),
    sa.Column('vitesse_assimilation', sa.Float(), nullable=True),
    sa.Column('capacite_memoire_travail', sa.Float(), nullable=True),
    sa.Column('tendance_impulsivite', sa.Float(), nullable=True),
    sa.Column('prefer_visual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id')
    )
    op.create_table('learner_competency_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('last_practice_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('nb_success', sa.Integer(), nullable=True),
    sa.Column('nb_failures', sa.Integer(), nullable=True),
    sa.Column('streak_correct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competence_id'], ['competences_cliniques.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_competency_mastery_id'), 'learner_competency_mastery', ['id'], unique=False)
    op.create_table('learner_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=True),
    sa.Column('type_objectif', sa.String(length=100), nullable=True),
    sa.Column('domaine_cible', sa.String(length=100), nullable=True),
    sa.Column('date_limite', sa.TIMESTAMP(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learner_misconceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=True),
    sa.Column('type_erreur', sa.String(length=255), nullable=True),
    sa.Column('frequence_apparition', sa.Integer(), nullable=True),
    sa.Column('resistance_correction', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learner_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=True),
    sa.Column('cle', sa.String(length=100), nullable=True),
    sa.Column('valeur', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learner_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('effectiveness', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('algorithme_recommandation', sa.String(length=100), nullable=True),
    sa.Column('ordered_case_ids', sa.JSON(), nullable=True, comment='Liste ordonnée des IDs des cas'),
    sa.Column('progression', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_id'), 'learning_paths', ['id'], unique=False)
    op.create_table('simulation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('cas_clinique_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('score_final', sa.Float(), nullable=True),
    sa.Column('temps_total', sa.Integer(), nullable=True),
    sa.Column('cout_virtuel_genere', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('raison_fin', sa.String(length=100), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('context_state', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cas_clinique_id'], ['cas_cliniques_enrichis.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('sender', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('intention_detectee', sa.String(length=100), nullable=True),
    sa.Column('sentiment_analyse', sa.String(length=50), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('interaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('action_category', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('action_content', sa.JSON(), nullable=True),
    sa.Column('response_latency', sa.Integer(), nullable=True),
    sa.Column('charge_cognitive_estimee', sa.Float(), nullable=True),
    sa.Column('est_pertinent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_logs_id'), 'interaction_logs', ['id'], unique=False)
    op.create_table('learner_affective_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('stress_level', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('motivation_level', sa.Float(), nullable=True),
    sa.Column('frustration_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_feedback_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_feedback_logs_id'), 'tutor_feedback_logs', ['id'], unique=False)
    op.create_table('tutor_motivational_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('intervention_type', sa.String(length=100), nullable=True),
    sa.Column('emotional_state_before', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_motivational_state_id'), 'tutor_motivational_state', ['id'], unique=False)
    op.create_table('tutor_scaffolding_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('competence_cible_id', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('indices_deja_donnes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['competence_cible_id'], ['competences_cliniques.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_scaffolding_state_id'), 'tutor_scaffolding_state', ['id'], unique=False)
    op.create_table('tutor_socratic_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('tactic_used', sa.String(length=100), nullable=True),
    sa.Column('target_concept', sa.String(length=255), nullable=True),
    sa.Column('step_in_dialogue', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_socratic_state_id'), 'tutor_socratic_state', ['id'], unique=False)
    op.create_table('tutor_strategies_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_strategies_history_id'), 'tutor_strategies_history', ['id'], unique=False)
    op.create_table('tutor_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('trigger_event_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('strategy_used', sa.String(length=100), nullable=True),
    sa.Column('action_choisie', sa.String(length=100), nullable=True),
    sa.Column('intervention_content', sa.Text(), nullable=True),
    sa.Column('rationale', sa.JSON(), nullable=True),
    sa.Column('succes_intervention', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['interaction_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_decisions_id'), 'tutor_decisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_decisions_id'), table_name='tutor_decisions')
    op.drop_table('tutor_decisions')
    op.drop_index(op.f('ix_tutor_strategies_history_id'), table_name='tutor_strategies_history')
    op.drop_table('tutor_strategies_history')
    op.drop_index(op.f('ix_tutor_socratic_state_id'), table_name='tutor_socratic_state')
    op.drop_table('tutor_socratic_state')
    op.drop_index(op.f('ix_tutor_scaffolding_state_id'), table_name='tutor_scaffolding_state')
    op.drop_table('tutor_scaffolding_state')
    op.drop_index(op.f('ix_tutor_motivational_state_id'), table_name='tutor_motivational_state')
    op.drop_table('tutor_motivational_state')
    op.drop_index(op.f('ix_tutor_feedback_logs_id'), table_name='tutor_feedback_logs')
    op.drop_table('tutor_feedback_logs')
    op.drop_table('learner_affective_states')
    op.drop_index(op.f('ix_interaction_logs_id'), table_name='interaction_logs')
    op.drop_table('interaction_logs')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('simulation_sessions')
    op.drop_index(op.f('ix_learning_paths_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_table('learner_strategies')
    op.drop_table('learner_preferences')
    op.drop_table('learner_misconceptions')
    op.drop_table('learner_goals')
    op.drop_index(op.f('ix_learner_competency_mastery_id'), table_name='learner_competency_mastery')
    op.drop_table('learner_competency_mastery')
    op.drop_table('learner_cognitive_profiles')
    op.drop_table('learner_achievements')
    op.drop_index(op.f('ix_learners_matricule'), table_name='learners')
    op.drop_index(op.f('ix_learners_id'), table_name='learners')
    op.drop_index(op.f('ix_learners_email'), table_name='learners')
    op.drop_table('learners')
    op.drop_index(op.f('ix_experts_id'), table_name='experts')
    op.drop_index(op.f('ix_experts_email'), table_name='experts')
    op.drop_table('experts')
    # ### end Alembic commands ###
