"""Add cas_symptomes association and update models

Revision ID: 4f66bc9b6081
Revises: 994203ee2537
Create Date: 2025-11-07 10:03:23.727581+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f66bc9b6081'
down_revision = '994203ee2537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cas_cliniques_enrichis', 'presentation_clinique',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Histoire du patient, symptômes présentés, etc.',
               existing_comment='Histoire générale du patient, antécédents, etc. (SANS la liste des symptômes)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cas_cliniques_enrichis', 'presentation_clinique',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Histoire générale du patient, antécédents, etc. (SANS la liste des symptômes)',
               existing_comment='Histoire du patient, symptômes présentés, etc.',
               existing_nullable=False)
    # ### end Alembic commands ###
