"""change embedding dimensions to 384

Revision ID: 5c3894aa1b50
Revises: eb403e41e275
Create Date: 2025-12-26 00:14:27.010127+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '5c3894aa1b50'
down_revision = 'eb403e41e275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cas_cliniques_enrichis', 'embedding_texte',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_comment='Embedding de la description textuelle du cas',
               existing_nullable=True)
    op.alter_column('images_medicales', 'embedding_vision',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_comment="Vecteur d'embedding pour la recherche par similarité visuelle",
               existing_nullable=True)
    op.alter_column('medicaments', 'embedding_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_comment="Vecteur d'embedding pour la recherche de médicaments similaires",
               existing_nullable=True)
    op.alter_column('pathologies', 'embedding_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_comment="Vecteur d'embedding pour la recherche sémantique",
               existing_nullable=True)
    op.alter_column('symptomes', 'embedding_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_comment="Vecteur d'embedding pour la recherche sémantique (ex: BioBERT)",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('symptomes', 'embedding_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_comment="Vecteur d'embedding pour la recherche sémantique (ex: BioBERT)",
               existing_nullable=True)
    op.alter_column('pathologies', 'embedding_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_comment="Vecteur d'embedding pour la recherche sémantique",
               existing_nullable=True)
    op.alter_column('medicaments', 'embedding_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_comment="Vecteur d'embedding pour la recherche de médicaments similaires",
               existing_nullable=True)
    op.alter_column('images_medicales', 'embedding_vision',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_comment="Vecteur d'embedding pour la recherche par similarité visuelle",
               existing_nullable=True)
    op.alter_column('cas_cliniques_enrichis', 'embedding_texte',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_comment='Embedding de la description textuelle du cas',
               existing_nullable=True)
    # ### end Alembic commands ###
