"""Create clinical_cases table

Revision ID: a6bc48307908
Revises: b2699b90c4a9
Create Date: 2025-11-07 09:29:53.852125+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'a6bc48307908'
down_revision = 'b2699b90c4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cas_cliniques_enrichis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_fultang', sa.String(length=100), nullable=True, comment='Identifiant unique provenant de Fultang (ou synthétique)'),
    sa.Column('hash_integrite', sa.String(length=64), nullable=True, comment="SHA-256 pour la preuve d'intégrité des données brutes"),
    sa.Column('pathologie_principale_id', sa.Integer(), nullable=True),
    sa.Column('donnees_brutes', sa.JSON(), nullable=True, comment='Données originales (ex: de Fultang) avant traitement'),
    sa.Column('presentation_clinique', sa.JSON(), nullable=False, comment='Histoire du patient, symptômes présentés, etc.'),
    sa.Column('donnees_paracliniques', sa.JSON(), nullable=True, comment='Résultats des examens pour ce cas spécifique'),
    sa.Column('evolution_patient', sa.Text(), nullable=True, comment="Description de l'évolution du patient pendant le cas"),
    sa.Column('images_associees_ids', sa.ARRAY(sa.Integer()), nullable=True, comment="Liste des IDs des images de la table 'images_medicales'"),
    sa.Column('sons_associes_ids', sa.ARRAY(sa.Integer()), nullable=True, comment="Liste des IDs des sons de la table 'sons_medicaux'"),
    sa.Column('medicaments_prescrits', sa.JSON(), nullable=True, comment='Liste des médicaments prescrits dans ce cas'),
    sa.Column('niveau_difficulte', sa.Integer(), nullable=True, comment='Difficulté du cas (1-5)'),
    sa.Column('duree_estimee_resolution_min', sa.Integer(), nullable=True, comment='Temps estimé pour résoudre le cas'),
    sa.Column('objectifs_apprentissage', sa.JSON(), nullable=True, comment='Liste des compétences à acquérir'),
    sa.Column('competences_requises', sa.JSON(), nullable=True, comment='Mapping Q-Matrix pour ce cas'),
    sa.Column('valide_expert', sa.Boolean(), nullable=True),
    sa.Column('expert_validateur', sa.String(length=255), nullable=True),
    sa.Column('date_validation', sa.Date(), nullable=True),
    sa.Column('qualite_donnees', sa.Integer(), nullable=True, comment='Qualité des données sources (1-5)'),
    sa.Column('nb_utilisations', sa.Integer(), nullable=True),
    sa.Column('note_moyenne_apprenants', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('taux_succes_diagnostic', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('embedding_texte', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment='Embedding de la description textuelle du cas'),
    sa.Column('embedding_global', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True, comment='Embedding multimodal fusionné (texte+image+son)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pathologie_principale_id'], ['pathologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cas_cliniques_enrichis_code_fultang'), 'cas_cliniques_enrichis', ['code_fultang'], unique=True)
    op.create_index(op.f('ix_cas_cliniques_enrichis_id'), 'cas_cliniques_enrichis', ['id'], unique=False)
    op.create_index(op.f('ix_cas_cliniques_enrichis_pathologie_principale_id'), 'cas_cliniques_enrichis', ['pathologie_principale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cas_cliniques_enrichis_pathologie_principale_id'), table_name='cas_cliniques_enrichis')
    op.drop_index(op.f('ix_cas_cliniques_enrichis_id'), table_name='cas_cliniques_enrichis')
    op.drop_index(op.f('ix_cas_cliniques_enrichis_code_fultang'), table_name='cas_cliniques_enrichis')
    op.drop_table('cas_cliniques_enrichis')
    # ### end Alembic commands ###
