"""Create competencies and prerequisites tables

Revision ID: afeac86179db
Revises: 03d192a5f522
Create Date: 2025-11-29 20:23:29.605930+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'afeac86179db'
down_revision = '03d192a5f522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competences_cliniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_competence', sa.String(length=50), nullable=False, comment="Code unique (ex: 'ANAMNESE_DOULEUR')"),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=True, comment='Ex: Anamnese, Examen_physique, Raisonnement, Technique'),
    sa.Column('niveau_bloom', sa.Integer(), nullable=True, comment='Niveau dans la taxonomie de Bloom (1-6)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objectifs_apprentissage', sa.JSON(), nullable=True, comment='Liste détaillée des objectifs'),
    sa.Column('criteres_maitrise', sa.JSON(), nullable=True, comment='Critères pour valider la compétence'),
    sa.Column('parent_competence_id', sa.Integer(), nullable=True),
    sa.Column('ordre_apprentissage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_competence_id'], ['competences_cliniques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competences_cliniques_categorie'), 'competences_cliniques', ['categorie'], unique=False)
    op.create_index(op.f('ix_competences_cliniques_code_competence'), 'competences_cliniques', ['code_competence'], unique=True)
    op.create_index(op.f('ix_competences_cliniques_id'), 'competences_cliniques', ['id'], unique=False)
    op.create_table('prerequis_competences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.Column('prerequis_id', sa.Integer(), nullable=False),
    sa.Column('type_relation', sa.String(length=50), nullable=True, comment='STRICT, RECOMMANDE, SUPPORTIF'),
    sa.Column('force_relation', sa.DECIMAL(precision=3, scale=2), nullable=True, comment='Force du lien (0-1)'),
    sa.ForeignKeyConstraint(['competence_id'], ['competences_cliniques.id'], ),
    sa.ForeignKeyConstraint(['prerequis_id'], ['competences_cliniques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prerequis_competences')
    op.drop_index(op.f('ix_competences_cliniques_id'), table_name='competences_cliniques')
    op.drop_index(op.f('ix_competences_cliniques_code_competence'), table_name='competences_cliniques')
    op.drop_index(op.f('ix_competences_cliniques_categorie'), table_name='competences_cliniques')
    op.drop_table('competences_cliniques')
    # ### end Alembic commands ###
