"""Create media table

Revision ID: b2699b90c4a9
Revises: 9aed193ba8b7
Create Date: 2025-11-07 07:45:54.209466+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'b2699b90c4a9'
down_revision = '9aed193ba8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_medicales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_examen', sa.String(length=100), nullable=False, comment='Ex: Radiographie, Échographie, Scanner'),
    sa.Column('sous_type', sa.String(length=100), nullable=True, comment='Ex: Thorax, Abdomen, Crâne'),
    sa.Column('pathologie_id', sa.Integer(), nullable=True),
    sa.Column('fichier_url', sa.String(length=500), nullable=False, comment='URL vers le fichier (S3, stockage local, etc.)'),
    sa.Column('fichier_miniature_url', sa.String(length=500), nullable=True, comment="URL vers une version miniature de l'image"),
    sa.Column('format_image', sa.String(length=20), nullable=True, comment='Ex: DICOM, PNG, JPEG'),
    sa.Column('taille_ko', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True, comment="Description générale de l'image ou du cas"),
    sa.Column('signes_radiologiques', sa.JSON(), nullable=True, comment='Signes spécifiques visibles (ex: opacité, épanchement)'),
    sa.Column('annotations', sa.JSON(), nullable=True, comment="Coordonnées et descriptions de zones d'intérêt"),
    sa.Column('interpretation_experte', sa.Text(), nullable=True, comment="Compte-rendu d'un radiologue expert"),
    sa.Column('diagnostic_differentiel', sa.JSON(), nullable=True, comment="Autres diagnostics possibles basés sur l'image"),
    sa.Column('niveau_difficulte', sa.Integer(), nullable=True, comment="Difficulté d'interprétation de l'image (1-5)"),
    sa.Column('qualite_image', sa.Integer(), nullable=True, comment="Qualité technique de l'image (1-5)"),
    sa.Column('embedding_vision', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment="Vecteur d'embedding pour la recherche par similarité visuelle"),
    sa.Column('valide_expert', sa.Boolean(), nullable=True),
    sa.Column('expert_validateur', sa.String(length=255), nullable=True),
    sa.Column('date_validation', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pathologie_id'], ['pathologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_medicales_id'), 'images_medicales', ['id'], unique=False)
    op.create_index(op.f('ix_images_medicales_pathologie_id'), 'images_medicales', ['pathologie_id'], unique=False)
    op.create_index(op.f('ix_images_medicales_type_examen'), 'images_medicales', ['type_examen'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_medicales_type_examen'), table_name='images_medicales')
    op.drop_index(op.f('ix_images_medicales_pathologie_id'), table_name='images_medicales')
    op.drop_index(op.f('ix_images_medicales_id'), table_name='images_medicales')
    op.drop_table('images_medicales')
    # ### end Alembic commands ###
