"""Add publication status to clinical cases

Revision ID: b6afb34f22d7
Revises: a0ee48d62174
Create Date: 2026-01-11 22:28:01.220042+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6afb34f22d7'
down_revision = 'a0ee48d62174'
branch_labels = None
depends_on = None


def upgrade() -> None:
    print("\n--- [LOG] DÉBUT de la migration 'b6afb34f22d7' (upgrade) ---")
    
    try:
        print("    -> Tentative de suppression de la contrainte 'learner_knowledge_concept_id_fkey'")
        op.drop_constraint(
            'learner_knowledge_concept_id_fkey',
            'learner_knowledge',
            type_='foreignkey'
        )
        print("    -> ✅ Contrainte supprimée.")
    except Exception as e:
        print(f"    -> ⚠️ Échec de la suppression de la contrainte (peut-être déjà supprimée) : {e}")

    try:
        print("    -> Tentative de suppression de la table 'concepts'")
        op.drop_table('concepts')
        print("    -> ✅ Table supprimée.")
    except Exception as e:
        print(f"    -> ⚠️ Échec de la suppression de la table (peut-être déjà supprimée) : {e}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_histories_id'), table_name='learning_histories')
    op.drop_table('learning_histories')
    op.drop_index(op.f('ix_learner_performances_id'), table_name='learner_performances')
    op.drop_table('learner_performances')
    op.drop_index(op.f('ix_learner_behaviors_id'), table_name='learner_behaviors')
    op.drop_table('learner_behaviors')
    op.drop_index(op.f('ix_concepts_id'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_learner_knowledge_id'), table_name='learner_knowledge')
    op.drop_table('learner_knowledge')
    op.add_column('cas_cliniques_enrichis', sa.Column('statut_publication', sa.String(length=50), nullable=False, comment='Statut du cas: brouillon, en_revision, valide, archive'))
    op.create_index(op.f('ix_cas_cliniques_enrichis_statut_publication'), 'cas_cliniques_enrichis', ['statut_publication'], unique=False)
    op.drop_index(op.f('ix_tutor_decisions_case_id'), table_name='tutor_decisions')
    op.drop_index(op.f('ix_tutor_decisions_learner_id'), table_name='tutor_decisions')
    op.drop_column('tutor_decisions', 'learner_id')
    op.drop_column('tutor_decisions', 'case_id')
    op.drop_column('tutor_decisions', 'metadata_snapshot')
    op.drop_column('tutor_socratic_state', 'updated_at')
    op.drop_column('tutor_socratic_state', 'current_step_focus')
    op.drop_column('tutor_socratic_state', 'last_question_asked')
    op.drop_column('tutor_socratic_state', 'dialogue_history')

    op.drop_constraint(
        'learner_knowledge_concept_id_fkey', # Le nom de la contrainte
        'learner_knowledge',                 # La table où elle se trouve
        type_='foreignkey'
    )
    # --------------------

    # 2. Maintenant, on peut supprimer la table
    op.drop_table('concepts')

    # ... reste du fichier (probablement l'ajout de la colonne 'statut_publication')
    op.add_column('cas_cliniques_enrichis', sa.Column('statut_publication', sa.String(length=50), nullable=False, server_default='brouillon'))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_socratic_state', sa.Column('dialogue_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('tutor_socratic_state', sa.Column('last_question_asked', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tutor_socratic_state', sa.Column('current_step_focus', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tutor_socratic_state', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('tutor_decisions', sa.Column('metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('tutor_decisions', sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tutor_decisions', sa.Column('learner_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_tutor_decisions_learner_id'), 'tutor_decisions', ['learner_id'], unique=False)
    op.create_index(op.f('ix_tutor_decisions_case_id'), 'tutor_decisions', ['case_id'], unique=False)
    op.drop_index(op.f('ix_cas_cliniques_enrichis_statut_publication'), table_name='cas_cliniques_enrichis')
    op.drop_column('cas_cliniques_enrichis', 'statut_publication')
    op.create_table('learner_knowledge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mastery_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('learner_knowledge_concept_id_fkey')),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('learner_knowledge_learner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learner_knowledge_pkey'))
    )
    op.create_index(op.f('ix_learner_knowledge_id'), 'learner_knowledge', ['id'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('concepts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('p_init', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('p_transit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('p_guess', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('p_slip', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='concepts_pkey'),
    sa.UniqueConstraint('name', name='concepts_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_concepts_id'), 'concepts', ['id'], unique=False)
    op.create_table('learner_behaviors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sessions_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activities_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_time_spent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('learner_behaviors_learner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learner_behaviors_pkey'))
    )
    op.create_index(op.f('ix_learner_behaviors_id'), 'learner_behaviors', ['id'], unique=False)
    op.create_table('learner_performances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('time_spent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('learner_performances_concept_id_fkey')),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('learner_performances_learner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learner_performances_pkey'))
    )
    op.create_index(op.f('ix_learner_performances_id'), 'learner_performances', ['id'], unique=False)
    op.create_table('learning_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('activity_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_spent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('learning_histories_learner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_histories_pkey'))
    )
    op.create_index(op.f('ix_learning_histories_id'), 'learning_histories', ['id'], unique=False)
    # ### end Alembic commands ###
