"""Add expert_validateur_id to ClinicalCase

Revision ID: bc127903e3d2
Revises: 16068309bdb8
Create Date: 2025-12-25 00:23:58.911118+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'bc127903e3d2'
down_revision = '16068309bdb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cas_cliniques_enrichis', sa.Column('expert_validateur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cas_cliniques_enrichis', 'experts', ['expert_validateur_id'], ['id'])
    op.drop_column('cas_cliniques_enrichis', 'expert_validateur')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cas_cliniques_enrichis', sa.Column('expert_validateur', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cas_cliniques_enrichis', type_='foreignkey')
    op.drop_column('cas_cliniques_enrichis', 'expert_validateur_id')
    # ### end Alembic commands ###
