"""Add Learner, Tracking and Tutor tables

Revision ID: bc4cda91a030
Revises: afeac86179db
Create Date: 2025-12-19 10:03:40.038591+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'bc4cda91a030'
down_revision = 'afeac86179db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
