"""Add secondary pathologies to clinical cases

Revision ID: de1d3372f456
Revises: 7108003f9629
Create Date: 2025-11-07 13:38:16.973024+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'de1d3372f456'
down_revision = '7108003f9629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cas_cliniques_enrichis', sa.Column('pathologies_secondaires_ids', sa.ARRAY(sa.Integer()), nullable=True, comment="Liste d'IDs de pathologies comorbides ou secondaires"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cas_cliniques_enrichis', 'pathologies_secondaires_ids')
    # ### end Alembic commands ###
