"""Create medications table

Revision ID: f29ac6884d1c
Revises: 8e5b38bb2891
Create Date: 2025-11-06 20:17:47.401019+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'f29ac6884d1c'
down_revision = '8e5b38bb2891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_commercial', sa.String(length=255), nullable=True),
    sa.Column('dci', sa.String(length=255), nullable=False, comment='Dénomination Commune Internationale'),
    sa.Column('classe_therapeutique', sa.String(length=255), nullable=True),
    sa.Column('forme_galenique', sa.String(length=100), nullable=True, comment='Ex: Comprimé, Sirop, Injectable'),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('voie_administration', sa.String(length=100), nullable=True, comment='Ex: Orale, IV, IM, Cutanée'),
    sa.Column('mecanisme_action', sa.Text(), nullable=True),
    sa.Column('indications', sa.JSON(), nullable=True),
    sa.Column('contre_indications', sa.JSON(), nullable=True),
    sa.Column('effets_secondaires', sa.JSON(), nullable=True),
    sa.Column('interactions_medicamenteuses', sa.JSON(), nullable=True),
    sa.Column('precautions_emploi', sa.Text(), nullable=True),
    sa.Column('posologie_standard', sa.JSON(), nullable=True, comment='Posologie standard par âge, poids, indication'),
    sa.Column('disponibilite_cameroun', sa.String(length=50), nullable=True, comment='Ex: Urbain, Rural, CHU_uniquement'),
    sa.Column('cout_moyen_fcfa', sa.Integer(), nullable=True),
    sa.Column('statut_prescription', sa.String(length=50), nullable=True, comment='Ex: Prescription_obligatoire, OTC'),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment="Vecteur d'embedding pour la recherche de médicaments similaires"),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicaments_classe_therapeutique'), 'medicaments', ['classe_therapeutique'], unique=False)
    op.create_index(op.f('ix_medicaments_dci'), 'medicaments', ['dci'], unique=False)
    op.create_index(op.f('ix_medicaments_id'), 'medicaments', ['id'], unique=False)
    op.create_index(op.f('ix_medicaments_nom_commercial'), 'medicaments', ['nom_commercial'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicaments_nom_commercial'), table_name='medicaments')
    op.drop_index(op.f('ix_medicaments_id'), table_name='medicaments')
    op.drop_index(op.f('ix_medicaments_dci'), table_name='medicaments')
    op.drop_index(op.f('ix_medicaments_classe_therapeutique'), table_name='medicaments')
    op.drop_table('medicaments')
    # ### end Alembic commands ###
