"""Add expert intelligence

Revision ID: 03d192a5f522
Revises: de1d3372f456
Create Date: 2025-11-07 14:06:32.502322+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d192a5f522'
down_revision = 'de1d3372f456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regles_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_regle', sa.String(length=50), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=True, comment='Ex: DIAGNOSTIC, THERAPEUTIQUE, PEDAGOGIQUE, ALERTE'),
    sa.Column('priorite', sa.Integer(), nullable=True, comment="Priorité d'exécution (1-10), 10 étant le plus prioritaire"),
    sa.Column('conditions', sa.JSON(), nullable=False, comment="Partie 'IF' de la règle, structurée en JSON"),
    sa.Column('actions', sa.JSON(), nullable=False, comment="Partie 'THEN' de la règle, structurée en JSON"),
    sa.Column('description_naturelle', sa.Text(), nullable=True, comment='Description de la règle en langage naturel'),
    sa.Column('justification_medicale', sa.Text(), nullable=True, comment='Source ou justification clinique de la règle'),
    sa.Column('expert_auteur', sa.String(length=255), nullable=True),
    sa.Column('date_validation', sa.Date(), nullable=True),
    sa.Column('est_active', sa.Boolean(), nullable=False),
    sa.Column('nb_activations', sa.Integer(), nullable=True),
    sa.Column('taux_succes', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regles_production_categorie'), 'regles_production', ['categorie'], unique=False)
    op.create_index(op.f('ix_regles_production_code_regle'), 'regles_production', ['code_regle'], unique=True)
    op.create_index(op.f('ix_regles_production_id'), 'regles_production', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regles_production_id'), table_name='regles_production')
    op.drop_index(op.f('ix_regles_production_code_regle'), table_name='regles_production')
    op.drop_index(op.f('ix_regles_production_categorie'), table_name='regles_production')
    op.drop_table('regles_production')
    # ### end Alembic commands ###
