"""Create symptoms table

Revision ID: 6eb5a7dba20c
Revises: 7995e67f8833
Create Date: 2025-11-06 19:20:35.224401+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '6eb5a7dba20c'
down_revision = '7995e67f8833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_icd10', sa.String(length=20), nullable=True, comment='Code international de la maladie (CIM-10)'),
    sa.Column('nom_fr', sa.String(length=255), nullable=False),
    sa.Column('nom_en', sa.String(length=255), nullable=True),
    sa.Column('nom_local', sa.String(length=255), nullable=True, comment='Noms locaux ou courants au Cameroun'),
    sa.Column('categorie', sa.String(length=100), nullable=True, comment='Ex: Infectieuse, Chronique, Parasitaire'),
    sa.Column('prevalence_cameroun', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Prévalence en % dans le contexte camerounais'),
    sa.Column('niveau_gravite', sa.Integer(), nullable=True, comment='Échelle de 1 (bénin) à 5 (critique)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('physiopathologie', sa.Text(), nullable=True, comment='Mécanisme de la maladie'),
    sa.Column('evolution_naturelle', sa.Text(), nullable=True, comment='Comment la maladie évolue sans traitement'),
    sa.Column('complications', sa.JSON(), nullable=True, comment='Complications possibles'),
    sa.Column('facteurs_risque', sa.JSON(), nullable=True, comment='Facteurs de risque associés'),
    sa.Column('prevention', sa.Text(), nullable=True, comment='Mesures de prévention'),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment="Vecteur d'embedding pour la recherche sémantique"),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pathologies_categorie'), 'pathologies', ['categorie'], unique=False)
    op.create_index(op.f('ix_pathologies_code_icd10'), 'pathologies', ['code_icd10'], unique=True)
    op.create_index(op.f('ix_pathologies_id'), 'pathologies', ['id'], unique=False)
    op.create_index(op.f('ix_pathologies_nom_fr'), 'pathologies', ['nom_fr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pathologies_nom_fr'), table_name='pathologies')
    op.drop_index(op.f('ix_pathologies_id'), table_name='pathologies')
    op.drop_index(op.f('ix_pathologies_code_icd10'), table_name='pathologies')
    op.drop_index(op.f('ix_pathologies_categorie'), table_name='pathologies')
    op.drop_table('pathologies')
    # ### end Alembic commands ###
