"""Add cas_symptomes association and update models

Revision ID: 7108003f9629
Revises: 4f66bc9b6081
Create Date: 2025-11-07 10:04:10.734115+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7108003f9629'
down_revision = '4f66bc9b6081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cas_symptomes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cas_symptomes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cas_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symptome_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('details_contextuels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment="Description narrative du symptôme dans ce cas (ex: 'Fièvre à 40°C depuis 3 jours')"),
    sa.ForeignKeyConstraint(['cas_id'], ['cas_cliniques_enrichis.id'], name=op.f('cas_symptomes_cas_id_fkey')),
    sa.ForeignKeyConstraint(['symptome_id'], ['symptomes.id'], name=op.f('cas_symptomes_symptome_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cas_symptomes_pkey'))
    )
    # ### end Alembic commands ###
