"""Create symptoms table

Revision ID: 7995e67f8833
Revises: 4b1e2599b918
Create Date: 2025-11-06 12:48:47.725270+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '7995e67f8833'
down_revision = '4b1e2599b918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('nom_local', sa.String(length=255), nullable=True, comment="Nom vernaculaire ou local, ex: 'Ntou-tou' pour la toux"),
    sa.Column('categorie', sa.String(length=100), nullable=True, comment='Catégorie fonctionnelle (ex: Respiratoire, Neurologique, Digestif)'),
    sa.Column('type_symptome', sa.String(length=50), nullable=True, comment='Type de symptôme (ex: Subjectif, Objectif, Signe clinique)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description détaillée du symptôme et de sa signification clinique.'),
    sa.Column('questions_anamnese', sa.JSON(), nullable=True, comment='Liste structurée de questions pour explorer ce symptôme (ex: PQRST)'),
    sa.Column('signes_alarme', sa.Boolean(), nullable=False, comment="Indique si ce symptôme est un signe de gravité ('red flag')"),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True, comment="Vecteur d'embedding pour la recherche sémantique (ex: BioBERT)"),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptomes_categorie'), 'symptomes', ['categorie'], unique=False)
    op.create_index(op.f('ix_symptomes_id'), 'symptomes', ['id'], unique=False)
    op.create_index(op.f('ix_symptomes_nom'), 'symptomes', ['nom'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symptomes_nom'), table_name='symptomes')
    op.drop_index(op.f('ix_symptomes_id'), table_name='symptomes')
    op.drop_index(op.f('ix_symptomes_categorie'), table_name='symptomes')
    op.drop_table('symptomes')
    # ### end Alembic commands ###
