"""Create symptoms table

Revision ID: 8e5b38bb2891
Revises: 6eb5a7dba20c
Create Date: 2025-11-06 19:31:00.822591+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5b38bb2891'
down_revision = '6eb5a7dba20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathologie_symptomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathologie_id', sa.Integer(), nullable=False),
    sa.Column('symptome_id', sa.Integer(), nullable=False),
    sa.Column('probabilite', sa.DECIMAL(precision=5, scale=4), nullable=True, comment="Probabilité d'apparition du symptôme pour cette pathologie P(symptôme|pathologie)"),
    sa.Column('sensibilite', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('specificite', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('phase_maladie', sa.String(length=50), nullable=True, comment='Phase de la maladie où le symptôme apparaît (ex: Précoce, Tardive)'),
    sa.Column('frequence', sa.String(length=50), nullable=True, comment="Fréquence d'apparition (ex: Constant, Fréquent, Occasionnel)"),
    sa.Column('est_pathognomonique', sa.Boolean(), nullable=True, comment='Si True, ce symptôme seul suffit presque à poser le diagnostic'),
    sa.Column('importance_diagnostique', sa.Integer(), nullable=True, comment="Échelle de 1 à 5 sur l'importance de ce symptôme pour le diagnostic"),
    sa.ForeignKeyConstraint(['pathologie_id'], ['pathologies.id'], ),
    sa.ForeignKeyConstraint(['symptome_id'], ['symptomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pathologie_symptomes')
    # ### end Alembic commands ###
