"""Add cas_symptomes association table

Revision ID: 994203ee2537
Revises: a6bc48307908
Create Date: 2025-11-07 09:49:25.031773+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '994203ee2537'
down_revision = 'a6bc48307908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cas_symptomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cas_id', sa.Integer(), nullable=False),
    sa.Column('symptome_id', sa.Integer(), nullable=False),
    sa.Column('details_contextuels', sa.JSON(), nullable=True, comment="Description narrative du symptôme dans ce cas (ex: 'Fièvre à 40°C depuis 3 jours')"),
    sa.ForeignKeyConstraint(['cas_id'], ['cas_cliniques_enrichis.id'], ),
    sa.ForeignKeyConstraint(['symptome_id'], ['symptomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cas_cliniques_enrichis', 'presentation_clinique',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Histoire générale du patient, antécédents, etc. (SANS la liste des symptômes)',
               existing_comment='Histoire du patient, symptômes présentés, etc.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cas_cliniques_enrichis', 'presentation_clinique',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Histoire du patient, symptômes présentés, etc.',
               existing_comment='Histoire générale du patient, antécédents, etc. (SANS la liste des symptômes)',
               existing_nullable=False)
    op.drop_table('cas_symptomes')
    # ### end Alembic commands ###
