"""Create therapeutic relations tables

Revision ID: 9aed193ba8b7
Revises: f29ac6884d1c
Create Date: 2025-11-06 20:44:30.949745+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aed193ba8b7'
down_revision = 'f29ac6884d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traitements_pathologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathologie_id', sa.Integer(), nullable=False),
    sa.Column('medicament_id', sa.Integer(), nullable=False),
    sa.Column('type_traitement', sa.String(length=50), nullable=True, comment='Ex: Premiere_intention, Alternative, Adjuvant'),
    sa.Column('ligne_traitement', sa.Integer(), nullable=True, comment='Ex: 1ère ligne, 2e ligne'),
    sa.Column('indication_precise', sa.Text(), nullable=True),
    sa.Column('efficacite_taux', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Taux de succès en %'),
    sa.Column('duree_traitement_jours', sa.Integer(), nullable=True),
    sa.Column('posologie_detaillee', sa.JSON(), nullable=True),
    sa.Column('niveau_preuve', sa.String(length=50), nullable=True, comment='Grade de recommandation (A, B, C)'),
    sa.Column('guidelines_source', sa.String(length=255), nullable=True, comment='Source (OMS, MINSANTE Cameroun, etc.)'),
    sa.Column('rang_preference', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicament_id'], ['medicaments.id'], ),
    sa.ForeignKeyConstraint(['pathologie_id'], ['pathologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traitements_symptomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptome_id', sa.Integer(), nullable=False),
    sa.Column('medicament_id', sa.Integer(), nullable=False),
    sa.Column('efficacite', sa.String(length=50), nullable=True, comment='Ex: Tres_efficace, Efficace, Modere'),
    sa.Column('rapidite_action', sa.String(length=100), nullable=True, comment='Ex: Immediate, <30min'),
    sa.Column('posologie_recommandee', sa.Text(), nullable=True),
    sa.Column('rang_preference', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicament_id'], ['medicaments.id'], ),
    sa.ForeignKeyConstraint(['symptome_id'], ['symptomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traitements_symptomes')
    op.drop_table('traitements_pathologies')
    # ### end Alembic commands ###
