"""change embedding dimensions to 384

Revision ID: a0ee48d62174
Revises: 5c3894aa1b50
Create Date: 2025-12-26 00:19:52.135785+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ee48d62174'
down_revision = '5c3894aa1b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
