"""fix expert_validateur relationship

Revision ID: eb403e41e275
Revises: bc127903e3d2
Create Date: 2025-12-25 00:30:17.468368+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'eb403e41e275'
down_revision = 'bc127903e3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
